<?php

/*
 * hook_ctools_plugin_directory
 */
function wl_panels_ctools_plugin_directory($module, $plugin) {
  if ($module == 'page_manager' || $module == 'panels' || $module == 'ctools') {
    return "plugins/$plugin";
  }
}

/**
* Implementation of hook_ctools_plugin_api().
*/
function wl_panels_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}



