<?php

/*
 *
 *This module needs some heavy refactoring
 *It basically on new project insert
 *looks up the project resources and compares them
 *against users and sends those users a message
 *
 *On new users it searchs their attributes and
 *compares them with the project attributes and
 *sends them a message.
 *
 *In order to improve, the message set needs to be
 *in a ctools plugin or field formatter.
 *
//  */
// function wl_lookup_theme($existing, $type, $theme, $path){
//  return array('relevant_projects' => array(
//       'variables' => array(
//         'nodestoshow' => NULL,
//       ),
//       'template' => 'templates/' . 'relevant-projects',
//     ),);
// }



// function wl_lookup_entity_insert($entity, $type)
//  {
//   if ($type == 'project')
//    {
//     projectresourceswl_lookup($entity, $type);
//     projectskillswl_lookup($entity, $type);
//    }
//   if ($type == 'user')
//    {
//     userprojectswl_lookupresources($entity, $type);
//     userprojectswl_lookupskills($entity, $type);
//    }
//  }
// function wl_lookup_entity_update($entity, $type)
//  {
//   if ($type == 'project')
//    {
//     projectresourceswl_lookup($entity, $type);
//     projectskillswl_lookup($entity, $type);
//    }
//  }
// function wl_lookup_entity_view($entity, $type)
//  {
//   if ($type == 'profile2' OR $type == 'user')
//    {
//     userprojectswl_lookupresources($entity, $type);
//     userprojectswl_lookupskills($entity, $type);
//    }
//    sendemailtousers($entity,$type);
//  }
// function projectresourceswl_lookup($entity, $type)
//  {
//   $projectresources = array();
//   foreach ($entity->field_project_resources['und'] as $key => $value)
//    {
//     array_push($projectresources, $value['tid']);
//    }
//   $query = new EntityFieldQuery();
//   $query->entityCondition('entity_type', 'profile2');
//   $result = $query->execute();
//   $pids   = array();
//   foreach ($result['profile2'] as $key => $value)
//    {
//     array_push($pids, $value->pid);
//    }
//   $profiles         = profile2_load_multiple($pids);
//   $profilestonotify = array();
//   foreach ($profiles as $key => $value)
//    {
//     if (!empty($value->field_project_resources['und']))
//      {
//       foreach ($value->field_project_resources['und'] as $value)
//        {
//         if (in_array($value['tid'], $projectresources))
//          {
//           array_push($profilestonotify, $key);
//          }
//        }
//      }
//    }
//   $profile                 = profile2_load('26');
//   $arrayofprojectresources = array();
//   $array1                  = field_get_items('node', $entity, 'field_project_resources');
//   foreach ($array1 as $inner)
//    {
//     if (!empty($inner['taxonomy_term']->name))
//      {
//       array_push($arrayofprojectresources, $inner['taxonomy_term']->name);
//      }
//    }
//   $name = $entity->name;
//   $msg  = $name;
//   $msg .= ' &#32;has posted a project &#32;';
//   $msg .= $entity->title;
//   $msg .= ' &#32;and needs the following resources: &#32;';
//   $msg .= implode(", ", $arrayofprojectresources);
//   $msg .= '. &#32;Can you help them out?';
//   $msg .= ' &#32;If you can, great! Just sign up &#32;';
//   $msg .= '<a href="' . '/node/' . $entity->vid . '">' . 'here.</a>';
//   $useridstonotify = array();
//   $profs           = profile2_load_multiple($profilestonotify);
//   foreach ($profs as $value)
//    {
//     array_push($useridstonotify, $value->uid);
//    }
//   foreach ($useridstonotify as $oneuser)
//    {
//     privatemsg_new_thread(array(
//       user_load($oneuser)
//     ), 'Someone needs your resource', $msg);
//    }
//  }
// function userprojectswl_lookupskills($entity, $type)
//  {
//   $query = new EntityFieldQuery();
//   $query->entityCondition('entity_type', 'profile2')->propertyCondition('uid', $entity->uid);
//   $result = $query->execute();
//   foreach ($result['profile2'] as $key => $value)
//    {
//    }
//   $profile              = profile2_load($value->pid);
//   $arrayofprofileskills = array();
//   if (!empty($profile->field_project_skills['und']))
//    {
//     foreach ($profile->field_project_skills['und'] as $key => $value)
//      {
//       array_push($arrayofprofileskills, $value['tid']);
//      }
//    }
//   $query = new EntityFieldQuery();
//   $query->entityCondition('entity_type', 'node')->entityCondition('bundle', 'project');
//   $result = $query->execute();
//   $nids   = array();
//   foreach ($result['node'] as $key => $value)
//    {
//     array_push($nids, $value->nid);
//    }
//   $projectstolookthrough = entity_load('node', $nids);
//   $relevantprojects      = array();
//   foreach ($projectstolookthrough as $key => $value)
//    {
//     if (!empty($value->field_project_skills['und']))
//      {
//       foreach ($value->field_project_skills['und'] as $value)
//        {
//         if (in_array($value['tid'], $arrayofprofileskills))
//          {
//           array_push($relevantprojects, $key);
//          }
//        }
//      }
//    }
//   $nodestoshow = entity_load('node', $relevantprojects);


//   if (!empty($nodestoshow))
//    {
//     //check out projects needs skills
//       return theme('relevant_projects', array('nodestoshow' => $nodestoshow));

//    }
//  }
// function userprojectswl_lookupresources($entity, $type)
//  {
//   $query = new EntityFieldQuery();
//   $query->entityCondition('entity_type', 'profile2')->propertyCondition('uid', $entity->uid);
//   $result = $query->execute();
//   foreach ($result['profile2'] as $key => $value)
//    {
//    }
//   $profile                 = profile2_load($value->pid);
//   $arrayofprofileresources = array();
//   if (!empty($profile->field_project_resources['und']))
//    {
//     foreach ($profile->field_project_resources['und'] as $key => $value)
//      {
//       array_push($arrayofprofileresources, $value['tid']);
//      }
//    }
//   $query = new EntityFieldQuery();
//   $query->entityCondition('entity_type', 'node')->entityCondition('bundle', 'project');
//   $result = $query->execute();
//   $nids   = array();
//   foreach ($result['node'] as $key => $value)
//    {
//     array_push($nids, $value->nid);
//    }
//   $projectstolookthrough = entity_load('node', $nids);
//   $relevantprojects      = array();
//   foreach ($projectstolookthrough as $key => $value)
//    {
//     if (!empty($value->field_project_resources['und']))
//      {
//       foreach ($value->field_project_resources['und'] as $value)
//        {
//         if (in_array($value['tid'], $arrayofprofileresources))
//          {
//           array_push($relevantprojects, $key);
//          }
//        }
//      }
//    }
//   $nodestoshow = entity_load('node', $relevantprojects);
//   if (!empty($nodestoshow))
//    {return theme('relevant_projects', array('nodestoshow'=>$nodestoshow));
//    }
//  }
// function projectskillswl_lookup($entity, $type)
//  {
//   $projectskills = array();
//   foreach ($entity->field_project_skills['und'] as $key => $value)
//    {
//     array_push($projectskills, $value['tid']);
//    }
//   $query = new EntityFieldQuery();
//   $query->entityCondition('entity_type', 'profile2');
//   $result = $query->execute();
//   $pids   = array();
//   foreach ($result['profile2'] as $key => $value)
//    {
//     array_push($pids, $value->pid);
//    }
//   $profiles         = profile2_load_multiple($pids);
//   $profilestonotify = array();
//   foreach ($profiles as $key => $value)
//    {
//     if (!empty($value->field_project_skills['und']))
//      {
//       foreach ($value->field_project_skills['und'] as $value)
//        {
//         if (in_array($value['tid'], $projectskills))
//          {
//           array_push($profilestonotify, $key);
//          }
//        }
//      }
//    }
//   $profile              = profile2_load('26');
//   $arrayofprojectskills = array();
//   $array1               = field_get_items('node', $entity, 'field_project_skills');
//   foreach ($array1 as $inner)
//    {
//     if (!empty($inner['taxonomy_term']->name))
//      {
//       array_push($arrayofprojectskills, $inner['taxonomy_term']->name);
//      }
//    }
//   $name = $entity->name;
//   $msg  = $name;
//   $msg .= ' &#32;has posted a project &#32;';
//   $msg .= $entity->title;
//   $msg .= ' &#32;and needs the following skills: &#32;';
//   $msg .= implode(", ", $arrayofprojectskills);
//   $msg .= '. &#32;Can you help them out?';
//   $msg .= ' &#32;If you can, great! Just sign up &#32;';
//   $msg .= '<a href="' . '/node/' . $entity->vid . '">' . 'here.</a>';
//   $useridstonotify = array();
//   $profs           = profile2_load_multiple($profilestonotify);
//   foreach ($profs as $value)
//    {
//     array_push($useridstonotify, $value->uid);
//    }
//   foreach ($useridstonotify as $oneuser)
//    {
//     privatemsg_new_thread(array(
//       user_load($oneuser)
//     ), 'Someone needs your resource', $msg);
//    }
//  }
// function sendemailtousers($entity, $type){
// //if ($type == 'user'){
// //   dpm($entity);
// //if ($entity->field_would_you_like_to_receive_['und'][0]['value'] == '1')
// //   {
// //      echo 'send email';
// //   }
// //}
// }
