<?php

/**
 * Implements hook_views_api().
 */
function wl_event_views_api($module, $api) {
  if ($module == 'views' && $api == 'views_default') {
    return array('version' => 2);
  }
  return array(
    'api' => 3,
    'template path' => drupal_get_path('module', 'wl_event') . '/templates',
  );
}

/**
 * Implements hook_menu().
 */
// can be used to do a lookup on a menu path to return json
// probably entity reference autocomplete does a similar thing
// function wl_event_menu() {
//   $items = array();
//   $items['wl_event/user/%'] = array(
//     'title' => t('project call back'),
//     'page callback' => '_wl_event_userlookup',
//     'page arguments' => array(
//       0,
//       1,
//       2
//     ),
//     'access arguments' => array(
//       'publish content'
//     ),
//     'type' => MENU_CALLBACK
//   );
//   return $items;
// }
// function _wl_event_userlookup($arg1, $arg2, $arg3) {
//   $query = new EntityFieldQuery();
//   $query->entityCondition('entity_type', 'node')
//   ->entityCondition('bundle', 'project')
//   ->propertyCondition('status', 1)
//   ->propertyCondition('uid', $arg3, '=');
//   $results = $query->execute();
//   header('Content-Type: application/json');
//   $data = drupal_json_encode($results);
//   echo $data;
// }


